<?php

/**
 * BaseQuestionTag
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $question_id
 * @property integer $tag_id
 * 
 * @method integer     getQuestionId()  Returns the current record's "question_id" value
 * @method integer     getTagId()       Returns the current record's "tag_id" value
 * @method QuestionTag setQuestionId()  Sets the current record's "question_id" value
 * @method QuestionTag setTagId()       Sets the current record's "tag_id" value
 * 
 * @package    qaeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7021 2010-01-12 20:39:49Z lsmith $
 */
abstract class BaseQuestionTag extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('question_tag');
        $this->hasColumn('question_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('tag_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}