<?php

/**
 * BaseAnswer
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $author_id
 * @property integer $question_id
 * @property string $comment
 * @property string $answer
 * @property string $question
 * @property Author $Author
 * @property Question $Question
 * 
 * @method integer  getAuthorId()    Returns the current record's "author_id" value
 * @method integer  getQuestionId()  Returns the current record's "question_id" value
 * @method string   getComment()     Returns the current record's "comment" value
 * @method string   getAnswer()      Returns the current record's "answer" value
 * @method string   getQuestion()    Returns the current record's "question" value
 * @method Author   getAuthor()      Returns the current record's "Author" value
 * @method Question getQuestion()    Returns the current record's "Question" value
 * @method Answer   setAuthorId()    Sets the current record's "author_id" value
 * @method Answer   setQuestionId()  Sets the current record's "question_id" value
 * @method Answer   setComment()     Sets the current record's "comment" value
 * @method Answer   setAnswer()      Sets the current record's "answer" value
 * @method Answer   setQuestion()    Sets the current record's "question" value
 * @method Answer   setAuthor()      Sets the current record's "Author" value
 * @method Answer   setQuestion()    Sets the current record's "Question" value
 * 
 * @package    qaeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7021 2010-01-12 20:39:49Z lsmith $
 */
abstract class BaseAnswer extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('answer');
        $this->hasColumn('author_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('question_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('comment', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('answer', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('question', 'string', null, array(
             'type' => 'string',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Author', array(
             'local' => 'author_id',
             'foreign' => 'id'));

        $this->hasOne('Question', array(
             'local' => 'question_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}