<?php

/**
 * BaseQuestion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property Answer $Best
 * @property Answer $Origin
 * @property Doctrine_Collection $Related
 * @property Doctrine_Collection $Tags
 * 
 * @method Answer              getBest()    Returns the current record's "Best" value
 * @method Answer              getOrigin()  Returns the current record's "Origin" value
 * @method Doctrine_Collection getRelated() Returns the current record's "Related" collection
 * @method Doctrine_Collection getTags()    Returns the current record's "Tags" collection
 * @method Question            setBest()    Sets the current record's "Best" value
 * @method Question            setOrigin()  Sets the current record's "Origin" value
 * @method Question            setRelated() Sets the current record's "Related" collection
 * @method Question            setTags()    Sets the current record's "Tags" collection
 * 
 * @package    qa
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7021 2010-01-12 20:39:49Z lsmith $
 */
abstract class BaseQuestion extends QA
{
    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Answer as Best', array(
             'local' => 'best_id',
             'foreign' => 'id'));

        $this->hasOne('Answer as Origin', array(
             'local' => 'origin_id',
             'foreign' => 'id'));

        $this->hasMany('Question as Related', array(
             'refClass' => 'QuestionRelation',
             'local' => 'from_id',
             'foreign' => 'to_id',
             'equal' => true));

        $this->hasMany('Tag as Tags', array(
             'refClass' => 'QuestionTag',
             'local' => 'question_id',
             'foreign' => 'tag_id'));
    }
}