<?php

/**
 * Answer
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    qaeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7021 2010-01-12 20:39:49Z lsmith $
 */
class Answer extends BaseAnswer
{
  public function isBest()
  {
    return $this->id === $this->Question->best_id;
  }
  
  public function setBest()
  {
    $this->Question->BestAnswer = $this;
    $this->Question->save();
  }
  
  public function isNewer()
  {
    return $this->Question->BestAnswer 
      && $this->Question->BestAnswer->created_at < $this->created_at;
  }
  
  public function getAuthorName()
  {
    return $this->author_id ? $this->Author->fullname : 'Anonymous';
  }
}