<?php

/**
 * Author
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    qaeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7021 2010-01-12 20:39:49Z lsmith $
 */
class Author extends BaseAuthor
{
  public function __toString()
  {
    return $this->name;
  }
}