<?php

/**
 * Question
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    qaeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7021 2010-01-12 20:39:49Z lsmith $
 */
class Question extends BaseQuestion
{
  public function getTitle()
  {
    $lines = explode("\n" ,$this->question);
    return $lines[0];
  }
  
  public function getBody()
  {
    $lines = explode("\n" ,$this->question);
    $dummy = array_shift($lines);
    return implode("\n", $lines);
  }
  
  /**
   * extracts tags from the provided text and connects them
   *
   * @return void
   * @author The Young Shepherd
   **/
  public function setQuestion($text)
  {
    $names = array_keys(Toolkit::extractTags($text));
    if (count($names) > 0)
    {
      $tags = Doctrine::getTable('Tag')->findOrCreateByName($names);
      $this->Tags->merge($tags);
    }
    return $this->_set('question', $text);
  }
  
  public function __toString()
  {
    return $this->getTitle();
  }
  
  public function hasBestAnswer()
  {
    return null !== $this->best_id;
  }
}