<?php

/**
 * Tag
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    qaeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7021 2010-01-12 20:39:49Z lsmith $
 */
class Tag extends BaseTag
{
  public function __toString()
  {
    return $this->name;
  }
  
  public function setName($name)
  {
    return $this->_set('name', strtolower($name));
  }
}