all:
  sfApplyPlugin:
    from:
      email: "no-reply@symfony-bangalore.org"
      fullname: "Symfony Bangalore Administrator sends you"

    # Configure the gmail symfony.bangalore account to use for sending mails
    mail_transport_class: Zend_Mail_Transport_Smtp
    mail_transport_host: smtp.gmail.com
    mail_transport_options:
      auth: login
      username: symfony.bangalore@gmail.com
      password: '1W#r5Y&i'
      ssl: tls
      port: 587
