<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/02/13 05:45:57

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=qaeet',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
