<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/02/13 06:31:44

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=qaeet',
  'username' => 'qaeet',
  'password' => 'qaeet',
  'name' => 'doctrine',
)),);
