sfGuardUserProfile:
  tableName: sf_guard_user_profile
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    user_id:
      type: integer(4)
      notnull: true
    email:
      type: string(80)
    fullname:
      type: string(80)
    validate:
      type: string(17)
  relations:
    User:
      class: sfGuardUser
      foreign: id
      local: user_id
      type: one  
      onDelete: cascade    
      foreignType: one
      foreignAlias: Profile

Question:
  actAs:
    Timestampable: ~
    Sluggable:
      unique: true
      fields: [title]
      canUpdate: true
  columns:
    question: string
    answer: string
    best_id: integer
    branch_id: integer
    author_id: integer(4)
  relations:
    BestAnswer:
      class: Answer
      local: best_id
      foreignType:  one
    BranchedAnswer:
      class: Answer
      local: branch_id
      foreignType:  one
    Related:
      class: Question
      refClass: QuestionRelation
      local: from_id
      foreign: to_id
      equal: true
    Author:
      class: sfGuardUserProfile
      local: author_id
      foreignAlias: Questions
    Tags:
      class:        Tag
      refClass:     QuestionTag
      local:        question_id
      foreign:      tag_id
      foreignAlias: Questions
      
Answer:
  actAs:
    Timestampable:
  columns:
    author_id: integer(4)
    reply_id: integer
    question_id: integer
    comment: string
    answer: string
    question: string
  relations:
    Author:
      class: sfGuardUserProfile
      local: author_id
      foreignAlias: Answers
    Question:
      foreignAlias: Answers 
    ReplyTo:
      class: Answer
      local: reply_id
      foreignAlias: Replies

QuestionRelation:
  columns:
    from_id:
      type: integer
      primary: true
    to_id:
      type: integer
      primary: true

QuestionTag:
  columns:
    question_id:
      type: integer
      primary: true
    tag_id:
      type: integer
      primary: true
  
Tag:
  actAs:
    Sluggable:
      unique: true
      fields: [name]
  columns:
    name:
      type: string(255)
      unique: true
