QA:
  actAs:
    NestedSet:
      hasManyRoots:   true
      rootColumnName: root_id
    Sluggable:
      unique:         true
      fields:         [slugFromTitle]
      canUpdate:      true
    Timestampable:  ~
    Doctrine_Template_Blameable:
      listener:       Doctrine_Template_Listener_Blameable_sfGuard
      columns:
        created:
          type:         string
          length:       128
        updated:
          type:         string
          length:       128
  columns:
    question:         string
    answer:           string
  relations:
    Root:
      class:        QA
      local:        root_id

Question:
  inheritance:
    extends: QA
    type: column_aggregation
    keyField: type
    keyValue: 1
  columns:
    best_id:          integer
    origin_id:        integer
  relations:
    # Forwards to the best Answer item in this tree
    Best:
      class:        Answer
      local:        best_id
      foreignType:  one
    # indicates if this item originates from another question
    Origin:
      class:        Answer
      local:        origin_id
      foreignAlias: Branches
    # Points to related QAs elsewhere
    Related:
      class:        Question
      refClass:     QuestionRelation
      local:        from_id
      foreign:      to_id
      equal:        true
    Tags:
      class:        Tag
      refClass:     QuestionTag
      local:        question_id
      foreign:      tag_id
      foreignAlias: Questions
  
Answer:
  inheritance:
    extends: QA
    type: column_aggregation
    keyField: type
    keyValue: 2
  columns:
    comment:          string
    reply_id:         integer
  relations:
    ReplyTo:
      class:        QA
      local:        reply_id
      foreignAlias: Replies
      
QuestionRelation:
  columns:
    from_id:
      type: integer
      primary: true
    to_id:
      type: integer
      primary: true

QuestionTag:
  columns:
    question_id:
      type: integer
      primary: true
    tag_id:
      type: integer
      primary: true
  
Tag:
  actAs:
    Sluggable:
      unique: true
      fields: [name]
  columns:
    name:
      type: string(255)
      unique: true

sfGuardUserProfile:
  tableName: sf_guard_user_profile
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    user_id:
      type: integer(4)
      notnull: true
    email:
      type: string(80)
    fullname:
      type: string(80)
    validate:
      type: string(17)
  relations:
    User:
      class: sfGuardUser
      foreign: id
      local: user_id
      type: one  
      onDelete: cascade    
      foreignType: one
      foreignAlias: Profile
